=== ESSeRE-Lab/qualitas.class-corpus/projects/argouml-0.34/argouml-sql/src/org/argouml/language/sql/domainmapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.argouml.org/Namespace/argouml-sql"
	xmlns:tns="http://www.argouml.org/Namespace/argouml-sql"
	elementFormDefault="qualified">

	<element name="mappings" type="tns:mappingsType"></element>


	<complexType name="mappingsType">
		<sequence>
			<element name="database" type="tns:databaseType"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="mappingType">
		<attribute name="umltype" type="string"></attribute>
		<attribute name="dbtype" type="string"></attribute>
	</complexType>

	<complexType name="databaseType">
		<sequence>
			<element name="mapping" type="tns:mappingType"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>
</schema>

=== ESSeRE-Lab/qualitas.class-corpus/projects/argouml-0.34/argouml-sql/src/org/argouml/language/sql/domainmapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:mappings xmlns:tns="http://www.argouml.org/Namespace/argouml-sql"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.argouml.org/Namespace/argouml-sql domainmapping.xsd ">

	<!-- Mappings for Firebird -->
	<tns:database name="org.argouml.language.sql.FirebirdSqlCodeCreator">
		<tns:mapping umltype="int" dbtype="INTEGER" />
		<tns:mapping umltype="String" dbtype="VARCHAR(200)" />
		<tns:mapping umltype="double" dbtype="DOUBLE PRECISION" />
		<tns:mapping umltype="char" dbtype="CHAR" />
		<tns:mapping umltype="float" dbtype="DOUBLE PRECISION" />
		<tns:mapping umltype="Text" dbtype="VARCHAR(4000)" />
	</tns:database>

	<!-- Mappings for MySQL -->
	<tns:database name="org.argouml.language.sql.MySqlCodeCreator">
		<tns:mapping umltype="int" dbtype="INTEGER" />
		<tns:mapping umltype="String" dbtype="VARCHAR(200)" />
		<tns:mapping umltype="double" dbtype="DOUBLE PRECISION" />
		<tns:mapping umltype="char" dbtype="CHAR" />
		<tns:mapping umltype="float" dbtype="DOUBLE PRECISION" />
		<tns:mapping umltype="Text" dbtype="LONGTEXT" />
	</tns:database>
</tns:mappings>
