=== ESSeRE-Lab/qualitas.class-corpus/projects/compiere-330/utils_dev/trl/compiereTrl.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--Compiere(tm) Version 2.5.1a/2004-03-15 - Smart ERP & CRM - Copyright (c) 1999-2004 Jorg Janke -->
<!--Compiere Translation file DTD -->
<!ELEMENT compiereTrl (row+)>
<!ATTLIST compiereTrl
	table CDATA #REQUIRED
	language CDATA #REQUIRED
>
<!ELEMENT row (value+)>
<!ATTLIST row
	trl CDATA #IMPLIED
	id CDATA #REQUIRED
>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value
	original CDATA #IMPLIED
	column CDATA #REQUIRED
>

=== ESSeRE-Lab/qualitas.class-corpus/projects/compiere-330/data/en_US/W_Store_Trl_en_US.xml
<?xml version="1.0" encoding="UTF-8"?><!--Compiere(r) Release 2.5.2f_2005-09-01 - Smart ERP & CRM - (c) 1999-2005 Compiere (r); Implementation: unknown - not supported--><!--<!DOCTYPE compiereTrl PUBLIC "-//ComPiere, Inc.//DTD Compiere Translation 1.0//EN" "http://www.compiere.org/dtd/compiereTrl.dtd">--><compiereTrl language="en_US" table="W_Store"><row id="11" trl="Y"><value column="EMailFooter" original=""></value><value column="EMailHeader" original=""></value><value column="WebInfo" original=""></value><value column="WebParam1" original="Compiere120x60.gif">Compiere120x60.gif</value><value column="WebParam2" original="&lt;h1&gt;Web Store&lt;/h1&gt;">&lt;h1&gt;Web Store&lt;/h1&gt;</value><value column="WebParam3" original="Parameter3">Parameter3</value><value column="WebParam4" original="Parameter4">Parameter4</value><value column="WebParam5" original="Parameter5">Parameter5</value><value column="WebParam6" original="Parameter6">Parameter6</value></row></compiereTrl>

=== ESSeRE-Lab/qualitas.class-corpus/projects/compiere-330/data/sv_SE/C_PaymentTerm_Trl_sv_SE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Compiere(tm) Release 2.5.1f_2004-09-09 - Smart ERP & CRM - Copyright (c) 1999-2004 Jorg Janke; Implementation: johan 20050616-0918 - Unsupported--><!--<!DOCTYPE compiereTrl PUBLIC "-//ComPiere, Inc.//DTD Compiere Translation 1.0//EN" "http://www.compiere.org/dtd/compiereTrl.dtd">--><compiereTrl language="sv_SE" table="C_PaymentTerm"><row id="100" trl="Y"><value column="Name" original="30 Net">30 Days Net</value><value column="Description" original=""/><value column="DocumentNote" original=""/></row><row id="105" trl="Y"><value column="Name" original="Immediate">Immediate</value><value column="Description" original=""/><value column="DocumentNote" original=""/></row><row id="106" trl="Y"><value column="Name" original="2%10 Net 30">2%10 Net 30</value><value column="Description" original="2% discount if paid in 10 days, net due in 30 days">2% discount if paid in 10 days, net due in 30 days</value><value column="DocumentNote" original="Payment Term Note: Long Term Contracts are eligible for payment discounts.">Payment Term Note: Long Term Contracts are eligible for payment discounts.</value></row><row id="107" trl="Y"><value column="Name" original="30 Days Net">30 Days Net</value><value column="Description" original=""/><value column="DocumentNote" original=""/></row><row id="108" trl="Y"><value column="Name" original="50% Immediate - 50% in 30 days">50% Immediate - 50% in 30 days</value><value column="Description" original=""/><value column="DocumentNote" original=""/></row><row id="1000000" trl="N"><value column="Name" original="Direkt">Immediate</value><value column="Description" original=""/><value column="DocumentNote" original=""/></row><row id="1000001" trl="N"><value column="Name" original="10 dagar netto">10 dagar netto</value><value column="Description" original="10 dagar netto">10 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000002" trl="N"><value column="Name" original="15 dagar netto">15 dagar netto</value><value column="Description" original="15 dagar netto">15 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000003" trl="N"><value column="Name" original="20 dagar netto">20 dagar netto</value><value column="Description" original="20 dagar netto">20 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000004" trl="N"><value column="Name" original="30 dagar netto">30 dagar netto</value><value column="Description" original="30 dagar netto">30 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000005" trl="N"><value column="Name" original="Kontant">Kontant</value><value column="Description" original="Betalas genast">Betalas genast</value><value column="DocumentNote" original=""/></row><row id="1000006" trl="N"><value column="Name" original="130 dagar netto">130 dagar netto</value><value column="Description" original="130 dagar netto">130 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000007" trl="N"><value column="Name" original="90 dagar netto">90 dagar netto</value><value column="Description" original="90 dagar netto">90 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000008" trl="N"><value column="Name" original="180 dagar netto">180 dagar netto</value><value column="Description" original="180 dagar netto">180 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000009" trl="N"><value column="Name" original="60 dagar netto">60 dagar netto</value><value column="Description" original="60 dagar netto">60 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000010" trl="N"><value column="Name" original="17 dagar netto">17 dagar netto</value><value column="Description" original="17 dagar netto">17 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000011" trl="N"><value column="Name" original="19 dagar netto">19 dagar netto</value><value column="Description" original="19 dagar netto">19 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000012" trl="N"><value column="Name" original="21 dagar netto">21 dagar netto</value><value column="Description" original="21 dagar netto">21 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000013" trl="N"><value column="Name" original="23 dagar netto">23 dagar netto</value><value column="Description" original="23 dagar netto">23 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000014" trl="N"><value column="Name" original="25 dagar netto">25 dagar netto</value><value column="Description" original="25 dagar netto">25 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000015" trl="N"><value column="Name" original="27 dagar netto">27 dagar netto</value><value column="Description" original="27 dagar netto">27 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000016" trl="N"><value column="Name" original="29 dagar netto">29 dagar netto</value><value column="Description" original="29 dagar netto">29 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000017" trl="N"><value column="Name" original="31 dagar netto">31 dagar netto</value><value column="Description" original="31 dagar netto">31 dagar netto</value><value column="DocumentNote" original=""/></row><row id="1000018" trl="N"><value column="Name" original="33 dagar netto">33 dagar netto</value><value column="Description" original="33 dagar netto">33 dagar netto</value><value column="DocumentNote" original=""/></row></compiereTrl>
